server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/category/**
        - id: ms-product-service
          uri: lb://ms-product-service
          predicates:
            - Path=/product/**
        - id: ms-matricula-service
          uri: lb://ms-matricula-service
          predicates:
            - Path=/estudiante/**
        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/curso/**
        - id: ms-pago-service
          uri: lb://ms-pago-service
          predicates:
            - Path=/pago/**

